19-06-2024 16:31:13:[INFO]:__main__:main:132 - Init ViT model... - [0:00:01.127026]
19-06-2024 16:31:14:[ERROR]:utils:load_checkpoint:32 - Error loading the model! [Errno 2] No such file or directory: './artifacts/train/vit-dog-breed-latest.pth.tar' - [0:00:02.192643]
19-06-2024 16:31:14:[INFO]:__main__:main:218 - Training has started for epoch 0 - [0:00:02.192797]
19-06-2024 16:31:15:[ERROR]:__main__:main:265 - Training stopped at epoch 0 due to 'images' - [0:00:02.921392]
19-06-2024 16:31:38:[INFO]:__main__:main:132 - Init ViT model... - [0:00:01.124058]
19-06-2024 16:31:39:[ERROR]:utils:load_checkpoint:32 - Error loading the model! [Errno 2] No such file or directory: './artifacts/train/vit-dog-breed-latest.pth.tar' - [0:00:02.206533]
19-06-2024 16:31:39:[INFO]:__main__:main:218 - Training has started for epoch 0 - [0:00:02.206718]
19-06-2024 16:31:40:[ERROR]:__main__:main:265 - Training stopped at epoch 0 due to Sequential.forward() got an unexpected keyword argument 'x' - [0:00:02.982650]
